protocol: 'https:'
host: 'embresearch.com'
sitetitle: 'Laboratory Design'
sitesubtitle: '組込よろず相談承り'
links:
#- text: 'top'
#  href: '/?page=top'
- text: 'つれづれ'
  href: '/?post'
- text: '昔のブログ'
  href: 'https://tfujikura.blogspot.com/'
- text: '楽屋'
  href: '/?post=20210904_name_of_post'
- text: 'POST'
  href: /?page=post'

sociallinks:
- icon: 'fa-twitter-square'
  href: 'https://twitter.com/emblabo65'
#- icon: 'fa-youtube-square'
#  href: 'https://www.youtube.com/'
- icon: 'fa-github-square'
  href: 'https://github.com/'
- icon: 'fa-graduation-cap'
  href: 'https://www.researchgate.net/profile/Toshiyuki-Fujikura'
- icon: 'fa-slideshare'
  href: 'https://www.slideshare.net/tfujikura'
- icon: 'fa-facebook-squar'
  href: 'https://www.facebook.com/tfujikura/'

#facebook: '@'
#twitter: '@'
#line: '@'
