protocol: 'https:'
host: 'embresearch.com'
sitetitle: 'Laboratory Design'
subtitle: '組込よろず相談承り'
links:
- text: 'top'
  href: '/?page=top'
- text: 'つれづれなるまま'
  href: '/?post'
- text: '昔のブログ'
  href: 'https://tfujikura.blogspot.com/'
